/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bananacar.ui;

import bananacar.dao.ChiTietTraGopDAO;
import bananacar.dao.HoaDonChiTietDAO;
import bananacar.dao.HoaDonDAO;
import bananacar.dao.HoaDonTraGopDAO;
import bananacar.dao.KhachHangDAO;
import bananacar.dao.XeDAO;
import bananacar.helper.Auth;
import bananacar.helper.MsgBox;

import bananacar.helper.XDate;
import bananacar.helper.XImage;
import bananacar.model.ChiTietTraGop;

import bananacar.model.HoaDon;
import bananacar.model.HoaDonChiTiet;
import bananacar.model.HoaDonTraGop;
import bananacar.model.KhachHang;
import bananacar.model.Xe;
import bananacar.model.XeDTO;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class BananaCarBanHangMain extends javax.swing.JFrame {

    /**
     * Creates new form BananaCarBanHangMain
     */
    HoaDonDAO daohd = new HoaDonDAO();
    HoaDonTraGopDAO daohdtg = new HoaDonTraGopDAO();
    XeDAO daoXe = new XeDAO();
    int rows = 0;
    ChiTietTraGopDAO daocttg = new ChiTietTraGopDAO();
    KhachHangDAO daokh = new KhachHangDAO();
    HoaDonChiTietDAO daohdct = new HoaDonChiTietDAO();
    public BananaCarBanHangMain() throws SQLException {
        initComponents();
        this.setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        fillTableToTable();
        fillComboBoxKhachHang();
        fillComboBoxKhachHangTG();
        clearForm();
        clearFormHDTG();
        init();
       
    }
    void openKhachHang(){
        new KhachHangJDialog(this, true).setVisible(true);
        fillComboBoxKhachHang();
    }
    
    void openHoaDon(){
    new DanhSachDonHangJDialog(this, true).setVisible(true);
    }
    void openThongTinTaiKhoan(){
        new NhanVienJDialog(this, true).setVisible(true);
    }
    void themHoaDonTraGop() throws SQLException{
        
            
            try {
            int dem = daohdtg.tongHoaDonTraGop();
            dem = dem + 1;
            String MaHDTG = "HDTG" + dem;
            txtMaHDTG.setText(MaHDTG);
        } catch (Exception e) {
            MsgBox.alert(this, "Có lỗi");
        }
        
    }
    void themHoaDon() throws SQLException{
        
            
            try {
            int dem = daohd.tongHoaDon();
            dem = dem + 1;
            String MaHD = "HD" + dem;
            txtMaHoaDon.setText(MaHD);
            
        } catch (Exception e) {
            MsgBox.alert(this, "Có lỗi");
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tabsHinhThuc = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnThemHD = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTongSoLuong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTongTienHang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cboMaKH = new javax.swing.JComboBox<>();
        cboGiamGia = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        txtThanhToan = new javax.swing.JButton();
        cboGTGT = new javax.swing.JComboBox<>();
        txtNgayBan = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtHoaHong = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtMaHDTG = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        txtMaNV2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTongSL1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTongTienXe1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cboSoNamTraGop = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        txtTraGopMoiThang = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtTOngTienTraGop = new javax.swing.JTextField();
        cboGiamGia1 = new javax.swing.JComboBox<>();
        cboMaKH2 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        txtNgayBan1 = new com.toedter.calendar.JDateChooser();
        cboThue1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tabsBanHang = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtChoNgoi = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtDongCo = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtSucManh = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtTayLaiTroLuc = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtTuiKhi = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtHTCBCP = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txtKeys = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_DanhSachXe = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 433));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hóa đơn"));

        jLabel4.setText("Mã hóa đơn");

        jLabel5.setText("Mã KH");

        btnThemHD.setText("Thêm");
        btnThemHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHDActionPerformed(evt);
            }
        });

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Mã nhân viên");

        jLabel7.setText("Ngày bán");

        jLabel8.setText("Tổng số lượng");

        txtTongSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongSoLuongActionPerformed(evt);
            }
        });

        jLabel9.setText("Giảm giá");

        jLabel10.setText("Thuế GTGT");

        jLabel12.setText("Tổng tiền hàng");

        cboMaKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboGiamGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%" }));
        cboGiamGia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboGiamGiaItemStateChanged(evt);
            }
        });

        jLabel24.setText("Thành tiền");

        txtThanhToan.setText("Thanh Toán");
        txtThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThanhToanActionPerformed(evt);
            }
        });

        cboGTGT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%" }));
        cboGTGT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboGTGTItemStateChanged(evt);
            }
        });

        txtNgayBan.setDateFormatString("dd/MM/yyyy");

        jLabel2.setText("Hoa hồng");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(txtThanhToan)
                .addGap(96, 96, 96))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(cboMaKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTongSoLuong)
                                    .addComponent(txtTongTienHang)
                                    .addComponent(cboGiamGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtThanhTien)
                                    .addComponent(cboGTGT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHoaHong))))
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtNgayBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemHD))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(cboMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(txtNgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTongSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTienHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cboGTGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoaHong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(txtThanhToan)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabsHinhThuc.addTab("Thanh toán ngay", jPanel10);

        jLabel13.setText("Mã hóa đơn trả góp");

        jButton4.setText("Thêm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel14.setText("Mã khách hàng");

        jLabel15.setText("Mã nhân viên");

        jButton5.setText("Thêm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel16.setText("Ngày bán");

        jLabel17.setText("Tổng số lượng");

        jLabel18.setText("Giảm giá");

        jLabel19.setText("Thuế GTGT");

        jLabel20.setText("Tổng tiền xe");

        jLabel21.setText("Số năm trả góp");

        cboSoNamTraGop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "3", "5" }));
        cboSoNamTraGop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSoNamTraGopItemStateChanged(evt);
            }
        });

        jLabel22.setText("Trả góp mỗi tháng");

        jLabel23.setText("Tổng tiền trả góp");

        cboGiamGia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%" }));
        cboGiamGia1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboGiamGia1ItemStateChanged(evt);
            }
        });

        cboMaKH2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton6.setText("Thanh toán");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtNgayBan1.setDateFormatString("dd/MM/yyyy");

        cboThue1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%" }));
        cboThue1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboThue1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaHDTG, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(cboMaKH2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel23)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTraGopMoiThang))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(18, 18, 18)
                            .addComponent(cboSoNamTraGop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(18, 18, 18)
                            .addComponent(txtTongTienXe1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMaNV2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNgayBan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTongSL1)
                                .addComponent(cboGiamGia1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboThue1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(txtTOngTienTraGop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(104, 104, 104))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaHDTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(cboMaKH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtMaNV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addComponent(txtNgayBan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTongSL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cboGiamGia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cboThue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTongTienXe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cboSoNamTraGop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtTraGopMoiThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(txtTOngTienTraGop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton6)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tabsHinhThuc.addTab("Trả góp", jPanel11);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setText("HÌNH THỨC THANH TOÁN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsHinhThuc)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabsHinhThuc))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã xe", "Tên xe", "Giá", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGioHang);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        tabsBanHang.addTab("Đơn hàng", jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(600, 732));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông số kĩ thuật"));

        jLabel25.setText("Chỗ ngồi");

        jLabel26.setText("Động cơ");

        jLabel27.setText("Sức mạnh");

        jLabel28.setText("Tay lái trợ lực");

        txtTayLaiTroLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTayLaiTroLucActionPerformed(evt);
            }
        });

        jLabel29.setText("Túi khí");

        jLabel30.setText("Hệ thống chống bó cứng phanh");

        txtHTCBCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHTCBCPActionPerformed(evt);
            }
        });

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Hình"));

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setMaximumSize(new java.awt.Dimension(300, 270));
        lblHinh.setMinimumSize(new java.awt.Dimension(300, 270));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(txtChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDongCo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSucManh)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTayLaiTroLuc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(81, 81, 81)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(txtTuiKhi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHTCBCP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSucManh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTuiKhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDongCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTayLaiTroLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHTCBCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm xe"));
        jPanel9.setPreferredSize(new java.awt.Dimension(685, 70));

        txtKeys.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKeysKeyReleased(evt);
            }
        });

        jLabel1.setText("Nhập mã xe hoặc tên xe");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtKeys, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        tbl_DanhSachXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã xe", "Tên xe", "Giá", "Số lượng tồn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_DanhSachXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DanhSachXeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_DanhSachXe);

        jPanel5.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tabsBanHang.addTab("Danh sách sản phẩm", jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsBanHang)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Tài khoản");

        jMenuItem1.setText("Thông tin tài khoản");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Đăng xuất");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Thoát");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Thống kê trong ngày");

        jMenuItem4.setText("Danh sách đơn hàng");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Tổng kết cuối ngày");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1533, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            this.themHoaDonTraGop();
            clearFormHDTG();
            themHDTG();
        } catch (SQLException ex) {
            MsgBox.alert(this, "Có lỗi");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.openKhachHang();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.openKhachHang();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.openHoaDon();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.openThongTinTaiKhoan();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnThemHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHDActionPerformed
        
            // TODO add your handling code here:
            
            try {
            themHoaDon();
            clearForm();
            themHD();
        } catch (Exception e) {
            MsgBox.alert(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btnThemHDActionPerformed

    private void txtTongSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongSoLuongActionPerformed

    private void tbl_DanhSachXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DanhSachXeMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.rows = tbl_DanhSachXe.rowAtPoint(evt.getPoint());
            if (this.rows >= 0) {
                this.edit();
                
            }
        }
        if(tabsHinhThuc.getSelectedIndex()== 0){
              if(evt.getClickCount() == 2){
                  if(txtMaHoaDon.getText().equals("")){
                    MsgBox.alert(this, "Vui lòng thêm mã hóa đơn");
                    return;
              }
              this.rows = tbl_DanhSachXe.rowAtPoint(evt.getPoint());
            if(this.rows >= 0){
                String tam = MsgBox.prompt(this, "Nhập số lượng");
                if(tam == null){
                    return;
                }else{
                    int soLuong = Integer.parseInt(tam);
                    addSP(soLuong);
                }
                
                
                fillToTableGioHang();       
                tabsBanHang.setSelectedIndex(0);
                
            }
            }
            
        }
        if (tabsHinhThuc.getSelectedIndex() == 1){
              if(evt.getClickCount() == 2){
                  if(txtMaHDTG.getText().equals("")){
                    MsgBox.alert(this, "Vui lòng thêm mã hóa đơn trả góp");
                    return;
              }
                    this.rows = tbl_DanhSachXe.rowAtPoint(evt.getPoint());
            if(this.rows >= 0){
                String tam = MsgBox.prompt(this, "Nhập số lượng");
                if(tam == null){
                    return;
                }else{
                    int soLuong = Integer.parseInt(tam);
                    addSPTG(soLuong);
                }
                
                
                fillToTableGioHangTG();       
                tabsBanHang.setSelectedIndex(0);
                
            }
            }
        }
        
        
    }//GEN-LAST:event_tbl_DanhSachXeMouseClicked

    private void txtHTCBCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHTCBCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHTCBCPActionPerformed

    private void txtTayLaiTroLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTayLaiTroLucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTayLaiTroLucActionPerformed

    private void txtKeysKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeysKeyReleased
        // TODO add your handling code here:
        fillTableToTable();
        clearForm();
    }//GEN-LAST:event_txtKeysKeyReleased

    private void cboGTGTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboGTGTItemStateChanged
        // TODO add your handling code here:
        demSoLuong();
    }//GEN-LAST:event_cboGTGTItemStateChanged

    private void cboGiamGiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboGiamGiaItemStateChanged
        // TODO add your handling code here:
        demSoLuong();
    }//GEN-LAST:event_cboGiamGiaItemStateChanged

    private void txtThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThanhToanActionPerformed
        // TODO add your handling code here:
        thanhToanHoaDon();
        init();
        gioHang = new HoaDonChiTiet();
        fillToTableGioHang();
        
    }//GEN-LAST:event_txtThanhToanActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dangXuat();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void cboGiamGia1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboGiamGia1ItemStateChanged
        // TODO add your handling code here:
        demSoLuongTG();
    }//GEN-LAST:event_cboGiamGia1ItemStateChanged

    private void cboThue1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboThue1ItemStateChanged
        // TODO add your handling code here:
        demSoLuongTG();
    }//GEN-LAST:event_cboThue1ItemStateChanged

    private void cboSoNamTraGopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSoNamTraGopItemStateChanged
        // TODO add your handling code here:
        demSoLuongTG();
    }//GEN-LAST:event_cboSoNamTraGopItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        thanhToanHoaDonTG();
        init();
        gioHangTG = new ChiTietTraGop();
        fillToTableGioHangTG();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BananaCarBanHangMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BananaCarBanHangMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BananaCarBanHangMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BananaCarBanHangMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BananaCarBanHangMain().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BananaCarBanHangMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemHD;
    private javax.swing.JComboBox<String> cboGTGT;
    private javax.swing.JComboBox<String> cboGiamGia;
    private javax.swing.JComboBox<String> cboGiamGia1;
    private javax.swing.JComboBox<String> cboMaKH;
    private javax.swing.JComboBox<String> cboMaKH2;
    private javax.swing.JComboBox<String> cboSoNamTraGop;
    private javax.swing.JComboBox<String> cboThue1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JTabbedPane tabsBanHang;
    private javax.swing.JTabbedPane tabsHinhThuc;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tbl_DanhSachXe;
    private javax.swing.JTextField txtChoNgoi;
    private javax.swing.JTextField txtDongCo;
    private javax.swing.JTextField txtHTCBCP;
    private javax.swing.JTextField txtHoaHong;
    private javax.swing.JTextField txtKeys;
    private javax.swing.JTextField txtMaHDTG;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaNV2;
    private com.toedter.calendar.JDateChooser txtNgayBan;
    private com.toedter.calendar.JDateChooser txtNgayBan1;
    private javax.swing.JTextField txtSucManh;
    private javax.swing.JTextField txtTOngTienTraGop;
    private javax.swing.JTextField txtTayLaiTroLuc;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JButton txtThanhToan;
    private javax.swing.JTextField txtTongSL1;
    private javax.swing.JTextField txtTongSoLuong;
    private javax.swing.JTextField txtTongTienHang;
    private javax.swing.JTextField txtTongTienXe1;
    private javax.swing.JTextField txtTraGopMoiThang;
    private javax.swing.JTextField txtTuiKhi;
    // End of variables declaration//GEN-END:variables
    DecimalFormat dcf = new DecimalFormat("###,###,###,###.###");
    
    private void fillTableToTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_DanhSachXe.getModel();
        model.setRowCount(0);
        try {
            String maxe = txtKeys.getText();
            String tenxe = txtKeys.getText();
            List<Xe> list  = daoXe.selectByKeyword(maxe, tenxe);
            
            for (Xe xe : list) {
                
                Object[] row = {
                    xe.getMaXe(),
                    xe.getTenXe(),
                    dcf.format(xe.getGiaBan()),
                    xe.getTonKho(),
                    
                };
                model.addRow(row);
            }
        } catch (Exception e) {
        }
    }
    
    void edit() {
        try {
            String maXe = (String) tbl_DanhSachXe.getValueAt(this.rows, 0);
            
            Xe model = daoXe.selectById(maXe);
            if (model != null) {
                this.setForm(model);
                
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
    private void setForm(Xe xe){
        
        if (xe.getHinh() != null) {
            lblHinh.setToolTipText(xe.getHinh());
            lblHinh.setIcon(XImage.read(xe.getHinh()));
            /*
            ImageIcon readLogo(String tenFile) đọc file trong thư mục logos theo tên file trả về ImageIcon
            void setIcon(ImageIcon icon) set Icon cho lbl
             */
        } else {
            lblHinh.setIcon(XImage.read("Photos-icon.png"));
        }
        txtChoNgoi.setText(String.valueOf(xe.getChoNgoi()));
        txtDongCo.setText(String.valueOf(xe.getDongCo()));
        txtSucManh.setText(String.valueOf(xe.getSucManh()));
        txtTayLaiTroLuc.setText(xe.isTayLaiTroLuc()?"Có":"Không");
        txtTuiKhi.setText(xe.isTuiKhi()?"Có":"Không");
        txtHTCBCP.setText(xe.isHTChongBoCungPhanh()?"Có":"Không");
    }
    
    private void clearForm() {
        try {
            HoaDon model2 = new HoaDon();
            Xe model = new Xe();
            this.setForm(model);
            model2.setNgayBan(XDate.now());
            this.setDangNhap(model2);
           
            txtTongSoLuong.setText("0");
            txtTongTienHang.setText("0.0");
            txtThanhTien.setText("0.0");
            txtHoaHong.setText("0.0");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void setDangNhap(HoaDon hd){
        
        txtMaNV.setText(Auth.user.getTenDangNhap());
        
        txtNgayBan.setDate(hd.getNgayBan());
        
    }
    private void setDangNhapTG(HoaDonTraGop hdtg){
        
        
        txtMaNV2.setText(Auth.user.getTenDangNhap());
        txtNgayBan1.setDate(hdtg.getNgayBan());
        
    }
    void fillComboBoxKhachHang(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaKH.getModel(); //kết nối model với cbo
        model.removeAllElements();   //xóa toàn bộ item của cbo
        try {
            List<KhachHang> list = daokh.selectAll();
            for (KhachHang kh : list) {
                model.addElement(kh); // lấy tên chuyên đề đưa vào cboChuyenDe  
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    List<Xe> listSPBan = daoXe.selectAll();
    HoaDonChiTiet gioHang = new HoaDonChiTiet();
    ChiTietTraGop gioHangTG = new ChiTietTraGop();
    HashMap<String, HoaDonChiTiet> listCart = new HashMap<>();
    public void fillToTableGioHang() {
        DefaultTableModel model = (DefaultTableModel) tblGioHang.getModel();
        model.setRowCount(0);
        Set<String> keySet = gioHang.getChiTietHoaDon().keySet();
        for (String key : keySet) {
            Xe xe = gioHang.getChiTietHoaDon().get(key).getXe();
            int soLuong = gioHang.getChiTietHoaDon().get(key).getSoLuong();
            
            Object[] row = {xe.getMaXe(), xe.getTenXe(), dcf.format(xe.getGiaBan()), soLuong, dcf.format(xe.getGiaBan()*soLuong)};
            model.addRow(row);
            
        }
        
    }
    
    public void fillToTableGioHangTG() {
        DefaultTableModel model = (DefaultTableModel) tblGioHang.getModel();
        model.setRowCount(0);
        Set<String> keySet = gioHangTG.getChiTietTraGop().keySet();
        for (String key : keySet) {
            Xe xe = gioHangTG.getChiTietTraGop().get(key).getXe();
            int soLuong = gioHangTG.getChiTietTraGop().get(key).getSoLuong();
            
            Object[] row = {xe.getMaXe(), xe.getTenXe(), dcf.format(xe.getGiaBan()), soLuong, dcf.format(xe.getGiaBan()*soLuong)};
            model.addRow(row);
            
        }
        
    }
    
    public void addSP(int soLuong){
        
        int index = tbl_DanhSachXe.getSelectedRow();
        Xe xe = listSPBan.get(index);
        
        
        XeDTO spDTO = new XeDTO(xe, soLuong);
        // add sản phẩm vừa chọn vào sv
        HoaDonChiTiet hdct = new HoaDonChiTiet();
        hdct.setMaHD(txtMaHoaDon.getText());
        hdct.setMaXe(xe.getMaXe());
        hdct.setDonGia(xe.getGiaBan());
        hdct.setSoLuong(soLuong);
        hdct.setThanhTien(xe.getGiaBan() * soLuong);
        daohdct.insert(hdct);
        gioHang.addProduct(spDTO);
        
        
        demSoLuong();
        
        fillToTableGioHang();
    }
    public void addSPTG(int soLuong){
        
        int index = tbl_DanhSachXe.getSelectedRow();
        Xe xe = listSPBan.get(index);
        
        
        XeDTO spDTO = new XeDTO(xe, soLuong);
        // add sản phẩm vừa chọn vào sv
        ChiTietTraGop cttg = new ChiTietTraGop();
        cttg.setMaHDTG(txtMaHDTG.getText());
        cttg.setMaXe(xe.getMaXe());
        cttg.setDonGia(xe.getGiaBan());
        cttg.setSoLuong(soLuong);
        cttg.setThanhTien(xe.getGiaBan() * soLuong);
        daocttg.insert(cttg);
        gioHangTG.addProduct(spDTO);
        
        
        demSoLuongTG();
        
        fillToTableGioHangTG();
    }
    
    void demSoLuong() {
        Set<String> keySet = gioHang.getChiTietHoaDon().keySet();
        int tongSL = 0;
        float TongTienHang = (float) 0.0;
        
        
        for (String key : keySet) {
            Xe xe = gioHang.getChiTietHoaDon().get(key).getXe();
            int soLuong = gioHang.getChiTietHoaDon().get(key).getSoLuong();
            int ma = gioHang.getMaHDCT();
            tongSL += soLuong;
            TongTienHang+= xe.getGiaBan()*soLuong;
           
        }
        float GiamGia = 0;
        if(cboGiamGia.getSelectedIndex() != 0){
           GiamGia = 0.1f;
        }
        float GTGT = 0;
        if(cboGTGT.getSelectedIndex() != 0){
           GTGT = 0.1f;
        }
        if(TongTienHang > 10000000000.0){
            cboGiamGia.setSelectedIndex(0);
        }
        float ThanhTien = (float) ((TongTienHang - TongTienHang*GiamGia) + TongTienHang*GTGT);
        txtThanhTien.setText(ThanhTien+"");
        txtTongSoLuong.setText(tongSL+"");
        txtTongTienHang.setText(TongTienHang+"");
        float HoaHong = (float) (ThanhTien * 0.01);
        txtHoaHong.setText(HoaHong+"");
    }
    void demSoLuongTG() {
        Set<String> keySet = gioHangTG.getChiTietTraGop().keySet();
        int tongSL = 0;
        float TongTienHang = (float) 0.0;
        
        
        for (String key : keySet) {
            Xe xe = gioHangTG.getChiTietTraGop().get(key).getXe();
            int soLuong = gioHangTG.getChiTietTraGop().get(key).getSoLuong();
            int ma = gioHangTG.getMaCTTG();
            tongSL += soLuong;
            TongTienHang+= xe.getGiaBan()*soLuong;
           
        }
        float GiamGia = 0;
        if(cboGiamGia1.getSelectedIndex() != 0){
           GiamGia = 0.1f;
        }
        float GTGT = 0;
        if(cboThue1.getSelectedIndex() != 0){
           GTGT = 0.1f;
        }
        if(TongTienHang > 15000000000.0){
            cboGiamGia1.setSelectedIndex(0);
        }
        float ThanhTien = (float) ((TongTienHang - TongTienHang*GiamGia) + TongTienHang*GTGT);
        txtTongTienXe1.setText(ThanhTien+"");
        txtTongSL1.setText(tongSL+"");
        float tongTienTraGop = (float) 0.0;
        float traGopMoiThang = (float) 0.0;
        if(cboSoNamTraGop.getSelectedIndex()== 0){
            tongTienTraGop = (float) (ThanhTien + ThanhTien * 0.15);
            traGopMoiThang = tongTienTraGop / 12;
        }else if(cboSoNamTraGop.getSelectedIndex() == 1){
            tongTienTraGop = (float) (ThanhTien + ThanhTien * 0.30);
            traGopMoiThang = tongTienTraGop / 36;
        }else{
            tongTienTraGop = (float) (ThanhTien + ThanhTien * 0.45);
            traGopMoiThang = tongTienTraGop / 60;
        }
        txtTraGopMoiThang.setText(traGopMoiThang + "");
        txtTOngTienTraGop.setText(tongTienTraGop + "");
    }
    
    private HoaDon getForm(){
        HoaDon hd = new HoaDon();
        hd.setMaHD(txtMaHoaDon.getText());
        hd.setMaKH(cboMaKH.getSelectedItem().toString());
        hd.setMaNhanVien(Auth.user.getTenDangNhap());
        hd.setNgayBan(txtNgayBan.getDate());
        hd.setGiamGia((float) (cboGiamGia.getSelectedIndex()==1?0.1:0.0));
        hd.setGTGT((float) (cboGTGT.getSelectedIndex()==1?0.1:0.0));
        hd.setThanhTien(Float.parseFloat(txtThanhTien.getText()));
        hd.setTongTienHang(Float.valueOf(txtTongTienHang.getText()));
        hd.setHoaHong(Float.parseFloat(txtHoaHong.getText()));
        hd.setTongSoLuong(Integer.valueOf(txtTongSoLuong.getText()));
       
        return hd;
    }
    
    void themHD(){
        HoaDon hd = getForm();
        try {
            daohd.insert(hd);
            fillTableToTable();
            this.clearForm();
            MsgBox.alert(this, "Thêm thành công");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Thêm thất bại");
        }
    }
    // thanh toan hoa don
    private void thanhToanHoaDon(){
        HoaDon hd = getForm();
        try {
            daohd.update(hd);
            
            this.clearForm();
            MsgBox.alert(this, "Thanh toán thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Thanh toán không thành công");
        }
    }
    private void thanhToanHoaDonTG(){
        HoaDonTraGop hdtg = getFormTG();
        try {
            daohdtg.update(hdtg);
            
            this.clearFormHDTG();
            MsgBox.alert(this, "Thanh toán thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Thanh toán không thành công");
        }
    }
    void init(){
        txtMaHoaDon.setEnabled(false);
        txtMaNV.setEnabled(false);
        txtNgayBan.setEnabled(false);
        txtTongSoLuong.setEnabled(false);
        txtTongTienHang.setEnabled(false);
        txtThanhTien.setEnabled(false);
        txtHoaHong.setEnabled(false);
        txtMaHoaDon.setText("");
        txtMaHDTG.setText("");
        txtMaHDTG.setEnabled(false);
        txtMaNV2.setEnabled(false);
        txtNgayBan1.setEnabled(false);
        txtTongSL1.setEnabled(false);
        txtTongTienXe1.setEnabled(false);
        txtTOngTienTraGop.setEnabled(false);
        txtTraGopMoiThang.setEnabled(false);
        
    }
    void dangXuat(){
        if(MsgBox.confirm(this, "Bạn muốn đăng xuất?")){
            
            this.dispose();
            new DangNhapJDialog(this, true).setVisible(true);
        }
    }
    private void clearFormHDTG() {
        try {
            HoaDonTraGop model2 = new HoaDonTraGop();
            Xe model = new Xe();
            this.setForm(model);
            model2.setNgayBan(XDate.now());
            this.setDangNhapTG(model2);
            
            txtTongSL1.setText("0");
            txtTongTienXe1.setText("0.0");
            txtTraGopMoiThang.setText("0.0");
            txtTOngTienTraGop.setText("0.0");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    void fillComboBoxKhachHangTG(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaKH2.getModel(); //kết nối model với cbo
        model.removeAllElements();   //xóa toàn bộ item của cbo
        try {
            List<KhachHang> list = daokh.selectAll();
            for (KhachHang kh : list) {
                model.addElement(kh); // lấy tên chuyên đề đưa vào cboChuyenDe  
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    void themHDTG(){
        HoaDonTraGop hdtg = getFormTG();
        try {
            daohdtg.insert(hdtg);
            fillTableToTable();
            this.clearFormHDTG();
            MsgBox.alert(this, "Thêm thành công");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Thêm thất bại");
        }
    }
    
    private HoaDonTraGop getFormTG(){
        HoaDonTraGop hdtg = new HoaDonTraGop();
        hdtg.setMaHDTG(txtMaHDTG.getText());
        hdtg.setMaKH(cboMaKH2.getSelectedItem().toString());
        hdtg.setMaNV(Auth.user.getTenDangNhap());
        hdtg.setNgayBan(txtNgayBan1.getDate());
        hdtg.setGiamGia((float) (cboGiamGia1.getSelectedIndex()==1?0.1:0.0));
        
        if(cboSoNamTraGop.getSelectedIndex() == 0){
            hdtg.setSoNamTraGop(1);
        }
        if(cboSoNamTraGop.getSelectedIndex() == 1){
            hdtg.setSoNamTraGop(3);
        }
        if(cboSoNamTraGop.getSelectedIndex() == 2){
            hdtg.setSoNamTraGop(5);
        }
        hdtg.setGTGT((float) (cboThue1.getSelectedIndex()==1?0.1:0.0));
        hdtg.setTongTienTraGop(Float.parseFloat(txtTOngTienTraGop.getText()));
        hdtg.setTongTienXe(Float.valueOf(txtTongTienXe1.getText()));
        hdtg.setTraGopMoiThang(Float.parseFloat(txtTraGopMoiThang.getText()));
        hdtg.setTongSoLuong(Integer.valueOf(txtTongSL1.getText()));
       
        return hdtg;
    }
}
