/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bananacar.ui;

import bananacar.dao.NguoiDungDAO;
import bananacar.helper.Auth;
import bananacar.helper.MsgBox;
import bananacar.model.NguoiDung;

/**
 *
 * @author USER
 */
public class DangNhapJDialog extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapJDialog
     */
    NguoiDungDAO daoND = new NguoiDungDAO();
    public DangNhapJDialog(java.awt.Frame parent, boolean modal) {
        
        initComponents();
        this.setLocationRelativeTo(null);
        init();
    }
    void init(){
        new ChaoJDialog(this, true).setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        btnDNQuanLy = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnDNBangHang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng nhập");
        setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bananacar/icons/108813b4ca5d4767cc4a6bafe030a5e9.gif"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("ĐĂNG NHẬP");

        jLabel3.setText("Tài khoản");

        jLabel4.setText("Mật khẩu");

        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        btnDNQuanLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bananacar/icons/data-management-icon.png"))); // NOI18N
        btnDNQuanLy.setText("Quản lý");
        btnDNQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNQuanLyActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bananacar/icons/Stop-Sign-icon.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnDNBangHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bananacar/icons/shop-icon.png"))); // NOI18N
        btnDNBangHang.setText("Bán hàng");
        btnDNBangHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNBangHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDNQuanLy)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDNBangHang))
                                    .addComponent(txtMatKhau)
                                    .addComponent(txtTenDangNhap)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(btnThoat)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDNQuanLy)
                    .addComponent(btnDNBangHang))
                .addGap(18, 18, 18)
                .addComponent(btnThoat))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void btnDNQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNQuanLyActionPerformed
        // TODO add your handling code here:
        dangNhap(1);
        
    }//GEN-LAST:event_btnDNQuanLyActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDNBangHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNBangHangActionPerformed
        // TODO add your handling code here:
        dangNhap(2);
    }//GEN-LAST:event_btnDNBangHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhapJDialog dialog = new DangNhapJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDNBangHang;
    private javax.swing.JButton btnDNQuanLy;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
     public void dangNhap(int chon) {
        String TenDangNhap = txtTenDangNhap.getText();
        String MatKhau = new String(txtMatKhau.getPassword());
        try {
            NguoiDung nd = daoND.timTenDangNhap(TenDangNhap);
            if (nd != null) {
                
                    String check = nd.getMatKhau();
                    if (MatKhau.equals(check)) {
                        boolean vaiTro = nd.isVaiTro();
                        if (chon == 1 && vaiTro == true) {
                            
                            Auth.user = nd;
                            MsgBox.alert(this, "Đăng nhập thành công!");
                            this.dispose();
                            new BananaCarQuanLyMain().setVisible(true);
                        } else if (chon == 1 && vaiTro == false) {
                            MsgBox.alert(this,"Bạn không được cấp quyền sử dụng chức năng này");
                        } else if (chon == 2) {
                            
                            Auth.user = nd;
                            MsgBox.alert(this, "Đăng nhập thành công!");
                            this.dispose();
                            new BananaCarBanHangMain().setVisible(true);
                        }
                    } else {
                        MsgBox.alert(this, "Sai mật khẩu");
                    }
                
                
            } else {
                MsgBox.alert(this, "Sai tên đăng nhập");
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Có lỗi: " + e.toString());
        }
    }
     void ketThuc() {
        if (MsgBox.confirm(this, "Bạn muốn kế thúc ứng dụng")) {
            System.exit(0);
        }

    }
}
