/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bananacar.ui;

import bananacar.dao.HangXeDAO;
import bananacar.dao.LoaiXeDAO;
import bananacar.dao.XeDAO;
import bananacar.helper.Auth;
import bananacar.helper.MsgBox;
import bananacar.helper.XDate;
import bananacar.helper.XImage;
import bananacar.helper.utilityHelper;
import bananacar.model.HangXe;
import bananacar.model.LoaiXe;
import bananacar.model.Xe;
import static java.awt.Color.pink;
import static java.awt.Color.white;
import java.io.File;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class DanhSachXeJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DanhSachXeJDialog
     */
    int rows = 0;
    XeDAO daoXe = new XeDAO();
    LoaiXeDAO daoLoaiXe = new LoaiXeDAO();
    HangXeDAO daoHangXe = new HangXeDAO();
    JFileChooser fileChooser = new JFileChooser();
    public DanhSachXeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.fillComboBoxHangXe();
        this.fillComboBoxLoaiXe();
        this.fillTableToTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabsXe = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaXe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenXe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboHangXe2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboLoaiXe2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtTonKho = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDMNN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDMLN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtChoNgoi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDongCo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSucManh = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cboTLTL = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cboTuiKhi = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cboHTPhanh = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtBaoHanh = new javax.swing.JTextField();
        lblHinh = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachXe = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtKeys = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("QUẢN LÝ XE");

        jLabel2.setText("Mã xe");

        txtMaXe.setName("Mã xe"); // NOI18N

        jLabel3.setText("Tên xe");

        txtTenXe.setName("Tên xe"); // NOI18N

        jLabel4.setText("Mã hãng xe");

        jLabel5.setText("Mã loại xe");

        cboLoaiXe2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiXe2.setSelectedIndex(-1);

        jLabel6.setText("Tồn kho");

        txtTonKho.setName("Tồn kho"); // NOI18N

        jLabel7.setText("Định mức nhỏ nhất");

        jLabel8.setText("Định mức lớn nhất");

        jLabel10.setText("Giá bán");

        jLabel11.setText("Hình");

        jLabel12.setText("Chỗ ngồi");

        txtChoNgoi.setName("Chỗ ngồi"); // NOI18N

        jLabel13.setText("Động cơ");

        txtDongCo.setName("Động cơ"); // NOI18N

        jLabel14.setText("Sức mạnh");

        txtSucManh.setName("Sức mạnh"); // NOI18N

        jLabel15.setText("Tay lái trợ lực");

        cboTLTL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Có", "Không" }));

        jLabel16.setText("Túi khí");

        cboTuiKhi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Có", "Không" }));

        jLabel17.setText("Hệ thống chống bó cứng phanh");

        cboHTPhanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Có", "Không" }));

        jLabel18.setText("Bảo hành");

        txtBaoHanh.setName("Bảo hành"); // NOI18N

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setMaximumSize(new java.awt.Dimension(250, 200));
        lblHinh.setMinimumSize(new java.awt.Dimension(250, 200));

        jButton1.setText("Chọn ảnh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sửa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Mới");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel19.setText("Trạng thái");

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn", "Hết" }));
        cboTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTrangThaiActionPerformed(evt);
            }
        });

        jLabel20.setText("Giá nhập");

        txtGiaNhap.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txtMaXe, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenXe)
                            .addComponent(jLabel4)
                            .addComponent(cboHangXe2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(cboLoaiXe2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(txtTonKho)
                            .addComponent(jLabel7)
                            .addComponent(txtDMNN)
                            .addComponent(jLabel8)
                            .addComponent(txtDMLN))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtChoNgoi)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(txtDongCo)
                                .addComponent(txtSucManh)
                                .addComponent(jLabel15)
                                .addComponent(cboTLTL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboTuiKhi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addComponent(cboHTPhanh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(17, 17, 17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addGap(124, 124, 124))
                                            .addComponent(txtBaoHanh, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(40, 40, 40)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(75, 75, 75))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel11)
                                        .addComponent(cboTrangThai, 0, 170, Short.MAX_VALUE)
                                        .addComponent(jLabel20)
                                        .addComponent(txtGiaNhap))
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboHangXe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDongCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboLoaiXe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSucManh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTLTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDMNN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTuiKhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel17)))
                    .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDMLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboHTPhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(23, 23, 23))
        );

        tabsXe.addTab("Cập nhập", jPanel1);

        tblDanhSachXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã xe", "Tên xe", "Tên hãng", "Tên loại", "Tồn kho", "ĐMNN", "ĐMLN", "Giá", "Giá nhập", "Bảo hành", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSachXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachXeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachXe);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm xe"));

        jLabel9.setText("Nhập mã xe hoặc tên xe");

        txtKeys.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKeysKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtKeys)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtKeys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsXe.addTab("Danh sách", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabsXe)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabsXe))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.selectImage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (utilityHelper.checkNullText(txtMaXe)
                && utilityHelper.checkNullText(txtTenXe)
//                && utilityHelper.checkNullText(txtNgaySinh)
                && utilityHelper.checkNullText(txtTonKho)
                && utilityHelper.checkNullText(txtDMNN)
                && utilityHelper.checkNullText(txtDMLN)
                && utilityHelper.checkNullText(txtBaoHanh)
                && utilityHelper.checkNullText(txtGiaBan)
                && utilityHelper.checkNullText(txtChoNgoi)
                && utilityHelper.checkNullText(txtDongCo)
                && utilityHelper.checkNullText(txtSucManh)
                && utilityHelper.checkNullText(txtGiaNhap)) {
            if (utilityHelper.checkMaKH(txtMaXe)
                    && utilityHelper.checkName(txtTenXe)
//                    && utilityHelper.checkDate(txtNgaySinh)
                    && utilityHelper.checkSoLuong(txtTonKho)
                    && utilityHelper.checkSoLuong(txtDMNN)
                    && utilityHelper.checkSoLuong(txtDMLN)
                    && utilityHelper.checkSoLuong(txtBaoHanh)
                    && utilityHelper.checkSoLuong(txtChoNgoi)
                    && utilityHelper.checkSoLuong(txtDongCo)
                    && utilityHelper.checkSoLuong(txtSucManh)
                    && utilityHelper.checkGia(txtGiaBan)
                    && utilityHelper.checkGia(txtGiaNhap)) {
                if (checkTrungMa(txtMaXe)) {
                    if (checkGiaCa(txtGiaNhap) && checkDinhMuc(txtDMLN)) {
                    this.insert();
                }
                } else {
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblDanhSachXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachXeMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.rows = tblDanhSachXe.rowAtPoint(evt.getPoint());
            if (this.rows >= 0) {
                this.edit();
                tabsXe.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_tblDanhSachXeMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (utilityHelper.checkNullText(txtTenXe)
//                && utilityHelper.checkNullText(txtNgaySinh)
                && utilityHelper.checkNullText(txtTonKho)
                && utilityHelper.checkNullText(txtDMNN)
                && utilityHelper.checkNullText(txtDMLN)
                && utilityHelper.checkNullText(txtBaoHanh)
                && utilityHelper.checkNullText(txtGiaBan)
                && utilityHelper.checkNullText(txtChoNgoi)
                && utilityHelper.checkNullText(txtDongCo)
                && utilityHelper.checkNullText(txtSucManh)
                && utilityHelper.checkNullText(txtGiaNhap))
                
                        {
            if (utilityHelper.checkName(txtTenXe)
//                    && utilityHelper.checkDate(txtNgaySinh)
                    && utilityHelper.checkName(txtTenXe)
//                    && utilityHelper.checkDate(txtNgaySinh)
                    && utilityHelper.checkSoLuong(txtTonKho)
                    && utilityHelper.checkSoLuong(txtDMNN)
                    && utilityHelper.checkSoLuong(txtDMLN)
                    && utilityHelper.checkSoLuong(txtBaoHanh)
                    && utilityHelper.checkSoLuong(txtChoNgoi)
                    && utilityHelper.checkSoLuong(txtDongCo)
                    && utilityHelper.checkSoLuong(txtSucManh)
                    && utilityHelper.checkGia(txtGiaBan)
                    && utilityHelper.checkGia(txtGiaNhap)) {
                if(checkGiaCa(txtGiaNhap) && checkDinhMuc(txtDMLN)){
                    update();
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtKeysKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeysKeyReleased
        // TODO add your handling code here:
        fillTableToTable();
        clearForm();
    }//GEN-LAST:event_txtKeysKeyReleased

    private void cboTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTrangThaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachXeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachXeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachXeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachXeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DanhSachXeJDialog dialog = new DanhSachXeJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboHTPhanh;
    private javax.swing.JComboBox<String> cboHangXe2;
    private javax.swing.JComboBox<String> cboLoaiXe2;
    private javax.swing.JComboBox<String> cboTLTL;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JComboBox<String> cboTuiKhi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JTabbedPane tabsXe;
    private javax.swing.JTable tblDanhSachXe;
    private javax.swing.JTextField txtBaoHanh;
    private javax.swing.JTextField txtChoNgoi;
    private javax.swing.JTextField txtDMLN;
    private javax.swing.JTextField txtDMNN;
    private javax.swing.JTextField txtDongCo;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtKeys;
    private javax.swing.JTextField txtMaXe;
    private javax.swing.JTextField txtSucManh;
    private javax.swing.JTextField txtTenXe;
    private javax.swing.JTextField txtTonKho;
    // End of variables declaration//GEN-END:variables
    private void fillTableToTable() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachXe.getModel();
        model.setRowCount(0);
        try {
            String maxe = txtKeys.getText();
            String tenxe = txtKeys.getText();
            List<Xe> list  = daoXe.selectByKeyword(maxe, tenxe);
            
            for (Xe xe : list) {
                daoHangXe.selectAll();
                Object[] row = {
                    xe.getMaXe(),
                    xe.getTenXe(),
                    xe.getMaHang(),
                    xe.getMaLoai(),
                    xe.getTonKho(),
                    xe.getDinhMucNhoNhat(),
                    xe.getDinhMucLonNhat(),
                    xe.getGiaBan(),
                    xe.getGiaNhap(),
                    xe.getBaoHanh(),
                    xe.isTrangThai()?"Còn hàng":"Hết hàng"
                };
                model.addRow(row);
            }
        } catch (Exception e) {
        }
    }
    void fillComboBoxHangXe() { // 
        
        DefaultComboBoxModel model2 = (DefaultComboBoxModel) cboHangXe2.getModel();//kết nối model với cbo
        
        model2.removeAllElements();
        try {
            List<HangXe> list = daoHangXe.selectAll();
            for (HangXe hx: list) {
                
                model2.addElement(hx.toString2());// lấy tên chuyên đề đưa vào cboChuyenDe  
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
    void fillComboBoxLoaiXe(){
        
        DefaultComboBoxModel model2 = (DefaultComboBoxModel) cboLoaiXe2.getModel();//kết nối model với cbo
        
        model2.removeAllElements();
        try {
            List<LoaiXe> list = daoLoaiXe.selectAll();
            for (LoaiXe lx: list) {
                
                model2.addElement(lx.toString2());// lấy tên chuyên đề đưa vào cboChuyenDe 
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
    private Xe getForm() {
        Xe xe = new Xe();
        
        xe.setMaXe(txtMaXe.getText());
        xe.setTenXe(txtTenXe.getText());
        xe.setMaHang((String) cboHangXe2.getSelectedItem());
        xe.setMaLoai((String) cboLoaiXe2.getSelectedItem());
        xe.setTonKho(Integer.valueOf(txtTonKho.getText()));
        xe.setDinhMucNhoNhat(Integer.valueOf(txtDMNN.getText()));
        xe.setDinhMucLonNhat(Integer.valueOf(txtDMLN.getText()));
        xe.setGiaBan(Float.valueOf(txtGiaBan.getText()));
        xe.setHinh(lblHinh.getToolTipText());
        xe.setTrangThai(cboTrangThai.getSelectedIndex() == 0);
        xe.setChoNgoi(Integer.valueOf(txtChoNgoi.getText()));
        xe.setDongCo(Integer.valueOf(txtDongCo.getText()));
        xe.setSucManh(Integer.valueOf(txtSucManh.getText()));
        xe.setTayLaiTroLuc(cboTLTL.getSelectedIndex() == 0);
        xe.setTuiKhi(cboTuiKhi.getSelectedIndex() == 0);
        xe.setHTChongBoCungPhanh(cboHTPhanh.getSelectedIndex() == 0);
        xe.setBaoHanh(Integer.valueOf(txtBaoHanh.getText()));
        xe.setGiaNhap(Float.valueOf(txtGiaNhap.getText()));
        return xe;
    }
    
    private void setForm(Xe xe){
        txtMaXe.setText(xe.getMaXe());
        txtTenXe.setText(xe.getTenXe());
        cboHangXe2.setSelectedIndex(1);
        cboLoaiXe2.setSelectedItem(1);
        txtTonKho.setText(String.valueOf(xe.getTonKho()));
        txtDMNN.setText(String.valueOf(xe.getDinhMucNhoNhat()));
        txtDMLN.setText(String.valueOf(xe.getDinhMucLonNhat()));
        txtGiaBan.setText(String.valueOf(xe.getGiaBan()));
        if (xe.getHinh() != null) {
            lblHinh.setToolTipText(xe.getHinh());
            lblHinh.setIcon(XImage.read(xe.getHinh()));
            /*
            ImageIcon readLogo(String tenFile) đọc file trong thư mục logos theo tên file trả về ImageIcon
            void setIcon(ImageIcon icon) set Icon cho lbl
             */
        } else {
            lblHinh.setIcon(XImage.read("Photos-icon.png"));
        }
        cboTrangThai.setSelectedIndex(xe.isTrangThai()?0:1);
        txtChoNgoi.setText(String.valueOf(xe.getChoNgoi()));
        txtDongCo.setText(String.valueOf(xe.getDongCo()));
        txtSucManh.setText(String.valueOf(xe.getSucManh()));
        cboTLTL.setSelectedIndex(xe.isTayLaiTroLuc()?0:1);
        cboTuiKhi.setSelectedIndex(xe.isTuiKhi()?0:1);
        cboHTPhanh.setSelectedIndex(xe.isHTChongBoCungPhanh()?0:1);
        txtBaoHanh.setText(String.valueOf(xe.getBaoHanh()));
        txtGiaNhap.setText(String.valueOf(xe.getGiaNhap()));
    }
    
//    void selectComboBox() {
//        try {
//            Xe xe = (Xe) cboHangXe.getSelectedItem();
//            
//        //lấy 1 Object được chọn từ combobox
//        //có thể điền và lấy 1 Object từ combobox
//        txtMaXe.setText(xe.getMaXe());
//        txtTenXe.setText(xe);
//        this.fillTableToTable();
//        
//        
//        tabsXe.setSelectedIndex(1);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        
//    }
    private void clearForm() {
        try {
            Xe model = new Xe();
            this.setForm(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void insert() {
        Xe xe = getFormThemXe();
        
        try {
            
            daoXe.insert(xe);
            this.fillTableToTable();
            this.clearForm();
            MsgBox.alert(this, "Thêm thành công \n Tồn kho = 0 \n Trạng thái: Hết hàng");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Thêm thất bại");
        }

    }
    
    void edit() {
        try {
            String maXe = (String) tblDanhSachXe.getValueAt(this.rows, 0);
            
            Xe model = daoXe.selectById(maXe);
            if (model != null) {
                this.setForm(model);
                
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
    void selectImage() {
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { //nếu người dùng đã chọn đc file
            File file = fileChooser.getSelectedFile();    //lấy file người dùng chọn
            XImage.save(file); //sao chép file đã chọn thư mục logos
            
                // Hiển thị hình lên form
                lblHinh.setIcon(XImage.read(file.getName())); //file.getName(); lấy tên của file
                
                //ImageIcon readLogo(String tenFile) đọc file trong thư mục logos theo tên file trả về ImageIcon
                //void setIcon(ImageIcon icon) set Icon cho lbl
                
                lblHinh.setToolTipText(file.getName());
            
        }
    }
    private void delete() {
        if (MsgBox.confirm(this, "Bạn muốn xóa ?")) {
            String maXe = txtMaXe.getText();
        try {
            daoXe.delete(maXe);
            fillTableToTable();
            this.clearForm();

            MsgBox.alert(this, "Xóa thành công");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Xóa không thành công");
        }
        }
        
    }
    private void update() {
        Xe xe = getForm();
        try {
            daoXe.update(xe);
            fillTableToTable();
            this.clearForm();
            MsgBox.alert(this, "Sửa thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Sửa không thành công");
        }
    }
    private Xe getFormThemXe() {
        Xe xe = new Xe();
        
        xe.setMaXe(txtMaXe.getText());
        xe.setTenXe(txtTenXe.getText());
        xe.setMaHang((String) cboHangXe2.getSelectedItem());
        xe.setMaLoai((String) cboLoaiXe2.getSelectedItem());
        txtTonKho.setText("0");
        cboTrangThai.setSelectedIndex(1);
        xe.setTonKho(Integer.valueOf(txtTonKho.getText()));
        xe.setDinhMucNhoNhat(Integer.valueOf(txtDMNN.getText()));
        xe.setDinhMucLonNhat(Integer.valueOf(txtDMLN.getText()));
        xe.setGiaBan(Float.valueOf(txtGiaBan.getText()));
        xe.setHinh(lblHinh.getToolTipText());
        xe.setTrangThai(cboTrangThai.getSelectedIndex() == 0);
        xe.setChoNgoi(Integer.valueOf(txtChoNgoi.getText()));
        xe.setDongCo(Integer.valueOf(txtDongCo.getText()));
        xe.setSucManh(Integer.valueOf(txtSucManh.getText()));
        xe.setTayLaiTroLuc(cboTLTL.getSelectedIndex() == 0);
        xe.setTuiKhi(cboTuiKhi.getSelectedIndex() == 0);
        xe.setHTChongBoCungPhanh(cboHTPhanh.getSelectedIndex() == 0);
        xe.setBaoHanh(Integer.valueOf(txtBaoHanh.getText()));
        xe.setGiaNhap(Float.valueOf(txtGiaNhap.getText()));
        return xe;
    }
    
    public boolean checkTrungMa(JTextField txt) {
        txt.setBackground(white);
        if (daoXe.selectById(txt.getText()) == null) {
            return true;
        } else {
            txt.setBackground(pink);
            MsgBox.alert(this, txt.getName() + " đã bị tồn tại.");
            return false;
        }
    }
    public boolean checkGiaCa(JTextField txt){
        Xe xe = new Xe();
        float giaNhap = Float.valueOf(txtGiaNhap.getText());
        float giaBan = Float.valueOf(txtGiaBan.getText());
        float tinhvon = (float) (giaBan * 0.7);
        txt.setBackground(white);
        if(tinhvon >= giaNhap){
            return true;
        }else {
            txt.setBackground(pink);
            MsgBox.alert(this, txt.getName() + " giá nhập phải nhỏ hơn giá bán tối thiểu 30%.");
            return false;
        }
    }
    
    public boolean checkDinhMuc(JTextField txt){
        Xe xe = new Xe();
        float dmln = Float.valueOf(txtDMLN.getText());
        float dmnn = Float.valueOf(txtDMNN.getText());
        
        txt.setBackground(white);
        if(dmln > dmnn){
            return true;
        }else {
            txt.setBackground(pink);
            MsgBox.alert(this, txt.getName() + " định mức lớn nhất phải lớn hơn định mức nhỏ nhất");
            return false;
        }
    }
    
}
